version: "3.5"

services:
  psql-beers:
    image: postgres:13.3-alpine
    hostname: postgresql-server
    labels:
      br.dev.multicode.author: "Andre Ferreira <andre.dev.linux@gmail.com>"
      br.dev.multicode.license: "MIT"
    expose:
      - '5432'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: mcbeers
      POSTGRES_PASSWORD: mcbeers
      POSTGRES_DB: mcbeers
      TZ: UTC